version: '3.4'

services:
  birthday-bot:
    image: birthday-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - redis
      - mongo
    env_file:
      - ".env"

  redis:
    image: redis:7.0.5-alpine
    restart: on-failure
    volumes:
      - redis-data:/data
  
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  


volumes:
  redis-data:
  mongo-data: