version: '3.4'

services:
  birthday-bot:
    image: birthday-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - redis
      - mongo
    env_file:
      - stack.env

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data
  
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-}
  


volumes:
  redis-data:
  mongo-data:
