version: '3.4'

services:
  birthday-bot:
    image: kulunchick/birthday-bot:dev
    command: bash -c "alembic upgrade heads && python -m bot"
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - redis
      - postgres
    environment:
      - ADMINS=${ADMINS:-[1568892912]}
      - TOKEN=${TOKEN}
      - DONATE_LINK=${DONATE_LINK}
      - USE_WEBHOOK=${USE_WEBHOOK}
      - WEB_SERVER_HOST=${WEB_SERVER_HOST}
      - WEB_SERVER_PORT=${WEB_SERVER_PORT}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - GOOGLE_TOKEN=${GOOGLE_TOKEN}

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}

  backup:
    image: eeshugerman/postgres-backup-s3:15
    environment:
      - SCHEDULE=${SCHEDULE}
      - BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS}
      - PASSPHRASE=${PASSPHRASE}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=backup
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}


volumes:
  redis-data:
  postgres-data:
