[tool.poetry]
name = "birthday-bot"
version = "0.1.0"
description = ""
authors = ["Kulunchick <nikolikrasovski@gmail.com>"]
readme = "README.md"
packages = [{include = "birthday_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = {version = "^3.0.0b8", allow-prereleases = true}
sqlalchemy = {extras = ["postgresql-asyncpg"], version = "^2.0.19"}
uvloop = {version = "^0.17.0", platform = "linux"}
structlog = "^23.1.0"
fluentogram = "^1.1.6"
apscheduler = "^3.10.1"
geopy = "^2.3.0"
redis = "^4.6.0"
pydantic-settings = "^2.0.2"
cachetools = "^5.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
