[tool.pdm]
[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.2.0",
    "pytest-asyncio>=0.20.3",
    "tox>=4.0.16",
]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Kulunchick", email = "nikolikrasovski@gmail.com"},
]
dependencies = [
    "aiogram>=3.0.0b6",
    "redis>=4.3.4",
    "APScheduler>=3.9.1.post1",
    "Jinja2>=3.1.2",
    "geopy>=2.3.0",
    "Babel>=2.11.0",
    "pydantic>=1.10.2",
    "python-dotenv>=0.21.0",
    "loguru>=0.6.0",
    "pytz>=2022.6",
    "motor[srv]>=3.1.1",
]
requires-python = ">=3.8"
license = {text = "AGPL-3.0"}
