version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:2024.01
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKER_HUB_PASSWORD
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
              docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
            fi
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:dev .
              docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:dev
            fi

workflows:
  deploy:
    jobs:
      - deploy
